# Defines general project information.
[project]
name = "textgen-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
# Requires Python version 3.13 or newer.
requires-python = ">=3.13"

# Lists the required packages for this service.
dependencies = [
    "flask>=2.1",          # The web framework for creating the API.
    "groq>=0.1",           # The official client library for the Groq API.
    "python-dotenv>=1.0.0",# Used to load the .env file when running outside Docker.
]
